# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-json
      - id: check-toml
      - id: end-of-file-fixer
        exclude_types: [csv, jupyter]
      - id: mixed-line-ending
        exclude_types: [csv, jupyter]
      - id: check-vcs-permalinks
  - repo: local
    hooks:
      - id: black
        name: black formatting
        language: system
        entry: black --check .
        types: [python]
      - id: isort
        name: isort imports
        language: system
        entry: isort --check-only .
        types: [python]
      - id: mypy
        name: typechecking using mypy
        language: system
        entry: mypy scripts/ --no-incremental --ignore-missing-imports
        pass_filenames: false
